package com.eebc.childrenministry.service.impl;

import com.eebc.childrenministry.entity.Guardian;
import com.eebc.childrenministry.repository.GuardianRepository;
import com.eebc.childrenministry.service.GuardianService;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

@Service
@RequiredArgsConstructor
public class GuardianServiceImpl implements GuardianService {

    @Autowired
    private GuardianRepository guardianRepository;

    @Autowired
    private BCryptPasswordEncoder encoder;

    private static final Logger logger = LoggerFactory.getLogger(GuardianServiceImpl.class);

    @Override
    public List<Guardian> getAll() {
        try {
            List<Guardian> guardians = guardianRepository.findAll();
            logger.info("Retrieved {} guardians from the repository.", guardians.size());
            return guardians;
        } catch (Exception e) {
            logger.error("Error retrieving guardians from the repository: {}", e.getMessage());
            return List.of();
        }
    }

    @Override
    public Guardian getGuardianById(String id) {
        try {
            return guardianRepository.findById(id)
                    .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Guardian not found"));
        } catch (Exception e) {
            logger.error("Error retrieving guardian with ID {}: {}", id, e.getMessage());
            return null;
        }
    }

    @Override
    public Guardian create(Guardian guardian) {
        try {
            guardian.setId(null); // Ensure ID is generated by db
            if (guardian.getActive() == null) guardian.setActive(true);
            if (guardian.getRelationship() == null) guardian.setRelationship("PARENT");
            if (guardian.getIsPrimary() == null) guardian.setIsPrimary(false);
            if (guardian.getAllowedPickup() == null) guardian.setAllowedPickup(true);
            guardian.setCreatedAt(LocalDateTime.now());
            Guardian savedGuardian = guardianRepository.save(guardian);
            logger.info("Created new guardian with ID: {}", savedGuardian.getId());
            return savedGuardian;
        } catch (Exception e) {
            logger.error("Error creating guardian: {}", e.getMessage());
            throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR, "Error creating guardian");
        }
    }

    @Override
    public Guardian update(String id, Guardian req) {
        try {
            Guardian existing = guardianRepository.findById(id)
                    .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Guardian not found"));

            // Update fields if provided
            if (req.getFirstName() != null) existing.setFirstName(req.getFirstName());
            if (req.getLastName() != null) existing.setLastName(req.getLastName());
            if (req.getEmail() != null) existing.setEmail(req.getEmail());
            if (req.getPhone() != null) existing.setPhone(req.getPhone());
            if (req.getRelationship() != null) existing.setRelationship(req.getRelationship());
            if (req.getIsPrimary() != null) existing.setIsPrimary(req.getIsPrimary());
            if (req.getAllowedPickup() != null) existing.setAllowedPickup(req.getAllowedPickup());
            if (req.getActive() != null) existing.setActive(req.getActive());

            existing.setUpdatedAt(LocalDateTime.now());
            Guardian updatedGuardian = guardianRepository.save(existing);
            logger.info("Updated guardian with ID: {}", updatedGuardian.getId());

            return updatedGuardian;
        } catch (Exception e) {
            logger.error("Error updating guardian with ID {}: {}", id, e.getMessage());
            throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR, "Error updating guardian");
        }
    }

    @Override
    // ── Set or update a guardian's kiosk PIN ──
    public void setPin(String guardianId, String rawPin) {
        // Validate PIN — 4 to 6 digits only
        if (rawPin == null || !rawPin.matches("\\d{4,6}")) {
            throw new ResponseStatusException(
                    HttpStatus.BAD_REQUEST, "PIN must be 4–6 digits"
            );
        }

        Guardian guardian = guardianRepository.findById(guardianId)
                .orElseThrow(() -> new ResponseStatusException(
                        HttpStatus.NOT_FOUND, "Guardian not found"
                ));

        guardian.setCheckinPinHash(encoder.encode(rawPin));
        guardian.setPinSetAt(LocalDateTime.now());
        guardian.setUpdatedAt(LocalDateTime.now());
        guardianRepository.save(guardian);
    }

    @Override
    // ── Remove a guardian's PIN ───────────────
    public void removePin(String guardianId) {
        Guardian guardian = guardianRepository.findById(guardianId)
                .orElseThrow(() -> new ResponseStatusException(
                        HttpStatus.NOT_FOUND, "Guardian not found"
                ));
        guardian.setCheckinPinHash(null);
        guardian.setPinSetAt(null);
        guardian.setUpdatedAt(LocalDateTime.now());
        guardianRepository.save(guardian);
    }

    // ── Kiosk: look up guardian by raw PIN ────
    // Iterates guardians with a PIN set and
    // BCrypt-matches — returns first match
    @Override
    public Optional<Guardian> findByPin(String rawPin) {
        if (rawPin == null || rawPin.isBlank()) return Optional.empty();

        return guardianRepository.findAllWithPin()
                .stream()
                .filter(g -> encoder.matches(rawPin, g.getCheckinPinHash()))
                .findFirst();
    }

    // ── Verify PIN without exposing guardian ──
    @Override
    public boolean verifyPin(String guardianId, String rawPin) {
        return guardianRepository.findById(guardianId)
                .map(g -> g.getCheckinPinHash() != null &&
                        encoder.matches(rawPin, g.getCheckinPinHash()))
                .orElse(false);
    }

    @Override
    public List<Guardian> getByFamily(String familyId) {
        return guardianRepository.findByFamilyId(familyId);
    }

    @Override
    public List<Guardian> getAuthorizedPickup(String familyId) {
        return guardianRepository.findByFamilyIdAndAllowedPickupTrue(familyId);
    }

}
